import './favorites/favorite-coctails';
import './favorites/favorite-ing';
import './common/dropdown-menu';
import './common/mobile-menu';
import './common/theme-toggler';
import './modals/open-close-modal';
import './common/footer';
import './common/dropdown-menu-mob';
import './common/theme-toggler-mobile';
